version: '2.2'
services:
  app:
    build: .
    command: npm run start:watch
    ports:
      - 3000
    env_file:
      - ./database.env
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  app-db:
    image: postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    env_file:
      - database.env

  psql:
    extends:
      service: app-db
    command: psql
    environment:
      - PGHOST=app-db

  pg_dump:
    extends:
      service: app-db
    command: bash -c "pg_dump > /dump/database.sql"
    volumes:
      - ./database/:/dump/
    environment:
      - PGHOST=app-db
